name: compile sigrok

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
  push

jobs:
  my_first_job:
    name: compile sigrok
    runs-on: "ubuntu-latest"
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            submodules: recursive
        - name: build sigrok
          run:  |
            docker run  --rm -v $PWD:/sigrok ghcr.io/xxlogic/sigrokdocker2:main sh /sigrok/build.sh
        - name: Upload pulseview artifacts
          uses: actions/upload-artifact@main
          with:
            name: pulseview
            path: build_release_64/pulseview/contrib/pulseview-*.exe
        - name: Upload sigrok-cli artifacts
          uses: actions/upload-artifact@main
          with:
            name: sigrok-cli
            path: build_release_64/sigrok-cli/contrib/sigrok-cli*.exe
            
            
